# Generated by Django 4.1.3 on 2022-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='srn',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
