# Generated by Django 4.1.3 on 2022-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_srn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='srn',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
